types:
  - SORT_DEST_EM01
  - SORT_DEST_EM02
  - TEMPERATURE_SENSOR_01

SORT_DEST_EM01:
  expire_in: 20min
  key: D01
  name: SORT_DEST
  values:
    - UID: index
    - DESTINATIONS:
        list:
          delimiter: ;
          type: int
    - LOOP: int
    - ALGO:
        enum:
          - PRIO
          - ANY


SORT_DEST_EM02:
  expire_in: 20min
  key: D02
  name: SORT_DEST
  values:
    - UID: index
    - DESTINATIONS:
        list:
          delimiter: ;
          type: int
    - LOOP: int
    - ALGO:
        enum:
          - PRIO
          - ANY

TEMPERATURE_SENSOR_01:
  expire_in: 20min
  key: T_S01
  name: TEMPERATURE_SENSOR
  value:
    - ID: index
    - TIMESTAMP: string
    - TEMPERATURE: real
  read_event:
    - type: mqtt
    - broker: localhost:1883
    - subscribe: SENSOR/01/TEMPERATURE
    - format: "%r"
    - insert:
        - ID: ink_index(0)
        - TIMESTAMP: timestamp
        - TEMPERATURE: $1
  send_event:
    - type: mqtt
    - broker: localhost:1883
    - topic: CALCULATED
    - prepare: mean(TEMPERATURE)
    - when:
      - count(TEMPERATURE) >= 3
      - reset: true


types:
  - TEMPERATURE_SENSOR_01

TEMPERATURE_SENSOR_01:
  expire_in: 20min
  key: T_S01
  name: TEMPERATURE_SENSOR
  values:
    - ID: index
    - TIMESTAMP: string
    - TEMPERATURE: real
    - MESSAGE: string
  read_event:
    type: mqtt
    broker: localhost:1883
    subscribe: SENSOR/01/TEMPERATURE
    format: "%r %s"
    insert:
      - ID: ink_index(0)
      - TIMESTAMP: timestamp
      - TEMPERATURE: $1
      - MESSAGE: $2
    read_event:
      type: mqtt
      broker: localhost:1884
      subscribe: SENSOR/01/TEMPERATURE
      format: "%r %s"
      insert:
        - ID: ink_index(0)
        - TIMESTAMP: timestamp
        - TEMPERATURE: $1
        - MESSAGE: $2
      read_event:
        type: mqtt
        broker: localhost:1885
        subscribe: SENSOR/01/TEMPERATURE
        format: "%r %s"
        insert:
          - ID: ink_index(0)
          - TIMESTAMP: timestamp
          - TEMPERATURE: $1
          - MESSAGE: $2
  send_event:
    - type: mqtt
    - broker: localhost:1883
    - topic: CALCULATED
    - prepare: mean(TEMPERATURE)
    - when:
        - count(TEMPERATURE) >= 3
        - reset: true