//
// Created by cefour on 11.05.22.
//

#ifndef DATACONTAINER_MESSAGEQUEUEDEACTIVATEDEXCEPTION_H
#define DATACONTAINER_MESSAGEQUEUEDEACTIVATEDEXCEPTION_H
#include "../api/ExceptionMacro.h"

CREATE_EXCEPTION_CLASS(MessageQueueDeactivateException)




#endif //DATACONTAINER_MESSAGEQUEUEDEACTIVATEDEXCEPTION_H
