//
// Created by cefour on 03.05.22.
//

#ifndef DATACONTAINER_MQTTMESSENGEREXCEPTION_H
#define DATACONTAINER_MQTTMESSENGEREXCEPTION_H

#include "../api/ExceptionMacro.h"

CREATE_EXCEPTION_CLASS(MqttMessengerException)
CREATE_EXCEPTION_CLASS(MqttDisconnectException)




#endif //DATACONTAINER_MQTTMESSENGEREXCEPTION_H
