//
// Created by cefour on 18.05.22.
//

#ifndef DATACONTAINER_STORAGENODEINSERTIONEXCEPTION_H
#define DATACONTAINER_STORAGENODEINSERTIONEXCEPTION_H
#include "../api/ExceptionMacro.h"


CREATE_EXCEPTION_CLASS(StorageNodeInsertionException)


#endif //DATACONTAINER_STORAGENODEINSERTIONEXCEPTION_H
